### ISSUE TITLE
Invalid argument: Expected dimension 92 at axis 0 of the input shaped [100,64] but got dimension 100

### ISSUE THREAD

**Issue by diorw** [Coder-nlper/chinese-ner-tf2#1]
```
Epoch 0 Loss 19.7172: : 1it [00:01,  1.71s/it]
Traceback (most recent call last):
  File "ner_train.py", line 187, in <module>
    train(train_set, train_ops, tokenize)
  File "ner_train.py", line 89, in train
    train_span_step(batch_data,batch_label_heads, batch_label_tails)
  File "/Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "/Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 555, in call
    outputs = execute.execute(
  File "/Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Expected dimension 92 at axis 0 of the input shaped [100,64] but got dimension 100
         [[node gradient_tape/ner_model/rel_tranformer/attention_block_1/relative_multi_head_attn_1/einsum_3/Einsum (defined at ner_train.py:79) ]] [Op:__inference_train_span_step_3206]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/ner_model/rel_tranformer/attention_block_1/relative_multi_head_attn_1/einsum_3/Einsum:
 gradient_tape/ner_model/rel_tranformer/attention_block_1/relative_multi_head_attn_1/MLCConcatV2Grad (defined at /Users/wda/miniforge3/envs/tensorflow2/lib/python3.8/site-packages/tensorflow/compiler/tf2mlcompute/ops/gen_mlc_ops.py:1452)  
 ner_model/rel_tranformer/embedding_lookup/Identity (defined at /Users/wda/Downloads/chinese-ner-tf2-master/model/./transformer/relative_transformer.py:23)
```

我的环境是conda tensorflow2.4 M1芯片的mac上。报了这个错能问一下为啥shape会不符合呢

**Comment by diorw** [comment]
我使用的是span会报这个，使用ctf就不会

**Comment by white-wolf-tech** [comment]
“Expected dimension 92 at axis 0 of the input shaped [100,64] but got dimension 100”。第一位维度，也就是batch_size，代码中设置的是(None,None)是动态的，现在代码获取的batch_size是92，而送入的是100？？看着应该是batch对不上了，检查下你的数据处理代码

**Comment by qq492947833** [comment]
This is a big problem,already have in tf2 now.We set inputshape 0 is None,but I dont know why it will raise this error.
